#!/usr/bin/env bash

set -eu

: ${GOOGLE_CREDENTIALS:?}
: ${GOOGLE_PROJECT_ID:?}

source deployments-src/ci/utils

setup_gcloud_cli "${GOOGLE_CREDENTIALS}"

gcloud --project "${GOOGLE_PROJECT_ID}" compute firewall-rules list --format json |\
   jq .[].name | \
   xargs  gcloud -q --project "${GOOGLE_PROJECT_ID}" compute firewall-rules delete
