#!/bin/bash

set -eu

# env
: ${GOOGLE_CREDENTIALS:?}
: ${ENVIRONMENT_NAME:?}
: ${WORKER_SECRETS:?}
: ${JUMPBOX_SSH_USER:?}
: ${JUMPBOX_SSH_KEY:?}

set +u
source deployments-src/ci/utils
source /etc/profile.d/chruby.sh
chruby ruby

remove_terraform_prefix terraform/metadata worker_ > metadata

jumpbox_external_ip=$( jq -r -e .jumpbox_external_ip metadata )
worker_internal_ip=$( jq -r -e .internal_ip metadata )

ssh_tunnel \
   "${JUMPBOX_SSH_KEY}" \
   "${JUMPBOX_SSH_USER}@${jumpbox_external_ip}" \
   "${worker_internal_ip}"

cp worker-state/*.json updated-worker-state/worker-state.json

echo "Updating WORKER..."
bosh -n create-env \
  --state updated-worker-state/worker-state.json \
  -l metadata \
  -l <( echo "${WORKER_SECRETS}" ) \
  -v concourse_release_path="$( realpath $PWD/concourse/*.tgz )" \
  -v garden_runc_release_path="$( realpath $PWD/garden-runc-release/*.tgz )" \
  -v bosh_cpi_release_path="$( realpath $PWD/bosh-cpi-release/*.tgz )" \
  -v stemcell_path="$( realpath $PWD/stemcell/*.tgz )" \
  -v os_conf_release_path="$( realpath $PWD/os-conf-release/*.tgz )" \
  -v "gcp_credentials_json='${GOOGLE_CREDENTIALS}'" \
  deployments-src/concourse/workers/${ENVIRONMENT_NAME}/worker.yml

echo "Successfully updated worker!"
