#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${BOSH_DIRECTOR_SECRETS:?}
: ${SSH_PRIVATE_KEY:?}

if [ -n "$SSH_PRIVATE_KEY" ]; then
  echo "$SSH_PRIVATE_KEY" > /tmp/bosh.pem
fi

read_with_escaped_newlines() {
  perl -pe 's|\n|\\n|' "$1"
}

yaml_to_json() {
  echo "$1" | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'
}

secrets_json="$(yaml_to_json "${BOSH_DIRECTOR_SECRETS}")"

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
cpi_dir="$( cd "${workspace_dir}/cpi-release" && pwd )"
bosh_dir="$( cd "${workspace_dir}/bosh-release" && pwd )"
stemcell_dir="$( cd "${workspace_dir}/stemcell" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_dir="$( cd "${workspace_dir}/output-src" && pwd )"

git clone "${deployments_dir}" "${output_dir}"

working_dir="$( cd "${output_dir}/bosh/" && pwd )"
mkdir -p "${working_dir}/assets/"
cp ${cpi_dir}/*.tgz "${working_dir}/assets/cpi.tgz"
cp ${bosh_dir}/*.tgz "${working_dir}/assets/bosh.tgz"
cp ${stemcell_dir}/*.tgz "${working_dir}/assets/stemcell.tgz"

pushd "${working_dir}" > /dev/null
  echo "Updating director..."
  ${bosh_cli} -n create-env \
    -l <(echo "${BOSH_DIRECTOR_SECRETS}") \
    -l "${terraform_config}/metadata" \
    # -v ssl_cert="${SSL_CERT}" \
    # -v ssl_key="${SSL_KEY}" \
    ./director.yml

  echo "Updating cloud config..."
  director_endpoint="$( jq -e -r .bosh_hostname "${terraform_config}/metadata" )"
  director_username="$( echo "${secrets_json}" | jq -e -r .director_admin_username )"
  director_password="$( echo "${secrets_json}" | jq -e -r .director_admin_password )"
  ${bosh_cli} -n update-cloud-config \
    --environment "${director_endpoint}" \
    --user "${director_username}" \
    --password "${director_password}" \
    ./cloud-config.yml
popd > /dev/null

echo "Successfully updated director!"
