#!/bin/bash

set -eu

# env
: ${ENVIRONMENT_NAME:?}
: ${WORKER_SECRETS:?}

set +u
source deployments-src/ci/utils
source /etc/profile.d/chruby.sh
chruby ruby

if [ -d testbed-info ]; then
    # - vcenter_resource_pool
    export WORKER_SECRETS=$(echo -e "$WORKER_SECRETS$(
      bosh int <(jq '.vc[0] | {
        vcenter_address: .ip,
        vcenter_user: .vimUsername,
        vcenter_password: .vimPassword
      }' testbed-info/testbed-info.json)
    )")
fi

cp worker-state/*.json updated-worker-state/worker-state.json

echo "Updating WORKER..."
bosh -n create-env \
  --state updated-worker-state/worker-state.json \
  -v concourse_release_path="$( realpath $PWD/concourse/*.tgz )" \
  -v bosh_cpi_release_path="$( realpath $PWD/bosh-cpi-release/*.tgz )" \
  -v stemcell_path="$( realpath $PWD/stemcell/*.tgz )" \
  -l <( echo "${WORKER_SECRETS}" ) \
  $( echo ${OPTIONAL_FLAGS} ) \
  --vars-store="creds.yml" \
  deployments-src/concourse/workers/${ENVIRONMENT_NAME}/worker.yml

echo "Successfully updated worker!"
