#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${GOOGLE_CREDENTIALS_JSON:?}
: ${BOSH_DIRECTOR_SECRETS:?}
: ${BOSH_ENVIRONMENT:?}
: ${BOSH_USER:?}
: ${BOSH_PASSWORD:?}
: ${ROOT_CA_PEM:?}
: ${ROOT_CA_KEY:?}
: ${DEFAULT_CA_JSON:?}

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
director_templates_dir="$( cd "${workspace_dir}/director-templates" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_dir="$( cd "${workspace_dir}/updated-director-state" && pwd )"

cp "${director_templates_dir}/bosh.yml" "${output_dir}"

internal_director_ip=$(jq -r -e .internal_director_ip ${terraform_config}/metadata)
# TODO: remove external IP once we have SSH tunnel
external_director_ip=$(jq -r -e .external_director_ip ${terraform_config}/metadata)

pushd "${output_dir}" > /dev/null
  echo "Updating director..."
  ${bosh_cli} -n create-env \
    --ops-file "${director_templates_dir}/use-gcp.yml" \
    --ops-file "${director_templates_dir}/external-ip.yml" \
    -l <(echo "${BOSH_DIRECTOR_SECRETS}") \
    -v "admin_user=${BOSH_USER}" \
    -v "admin_password=${BOSH_PASSWORD}" \
    -v "default_ca=unused" \
    -v "default_ca=${DEFAULT_CA_JSON}" \
    -v "gcp_credentials_json=${GOOGLE_CREDENTIALS_JSON}" \
    -l "${terraform_config}/metadata" \
    --vars-store /tmp/please-delete-me-i-hope \
    ./bosh.yml
  rm creds.yml /tmp/please-delete-me-i-hope
popd > /dev/null

echo "Successfully updated director!"
