#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${GOOGLE_CREDENTIALS:?}
: ${NATBOX_SECRETS:?}
: ${SUBNET_NAME:?}

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
nat_state_dir="$( cd "${workspace_dir}/natbox-state" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

terraform_metadata="$( cat ${terraform_config}/metadata | jq -e .${SUBNET_NAME} )"
natbox_tags=$(echo "${terraform_metadata}" | jq -e -r .natbox_tags)

# outputs
output_dir="$( cd "${workspace_dir}/updated-natbox-state" && pwd )"

cp ${nat_state_dir}/*.json "${output_dir}/natbox-state.json"

pushd "${workspace_dir}" > /dev/null
  echo "Updating NAT..."
  ${bosh_cli} -n create-env \
    --state "${output_dir}/natbox-state.json" \
    -l <( echo "${terraform_metadata}" ) \
    -l <( echo "${NATBOX_SECRETS}" ) \
    -v "natbox_tags=${natbox_tags}" \
    -v "gcp_credentials_json='${GOOGLE_CREDENTIALS}'" \
    ${deployments_dir}/natbox/natbox.yml
popd > /dev/null

echo "Successflly updated nat!"
