#!/bin/bash

set -eu

# env
: ${GOOGLE_CREDENTIALS:?}
: ${ENVIRONMENT_NAME:?}
: ${WORKER_SECRETS:?}
: ${RUBY_VERSION:?}
: ${JUMPBOX_SSH_USER:?}
: ${JUMPBOX_SSH_KEY:?}

set +u
source deployments-src/ci/utils
source /etc/profile.d/chruby.sh
chruby $RUBY_VERSION

ln -s $PWD/concourse-and-garden/concourse-*.tgz concourse-and-garden/concourse-release.tgz
ln -s $PWD/concourse-and-garden/garden-runc-*.tgz concourse-and-garden/garden-runc-release.tgz

remove_terraform_prefix terraform/metadata worker_ > metadata

jumpbox_external_ip=$( jq -r -e .jumpbox_external_ip metadata )
worker_internal_ip=$( jq -r -e .internal_ip metadata )

ssh_tunnel \
   "${JUMPBOX_SSH_KEY}" \
   "${JUMPBOX_SSH_USER}@${jumpbox_external_ip}" \
   "${worker_internal_ip}"

cp worker-state/*.json updated-worker-state/worker-state.json

echo "Updating WORKER..."
bosh2 -n create-env \
  --state updated-worker-state/worker-state.json \
  -l metadata \
  -l <( echo "${WORKER_SECRETS}" ) \
  -v "gcp_credentials_json='${GOOGLE_CREDENTIALS}'" \
  deployments-src/${ENVIRONMENT_NAME}/worker.yml

echo "Successfully updated worker!"
