#!/bin/bash

set -eu

# env
: ${ENVIRONMENT_NAME:?}
: ${WORKER_SECRETS:?}

set +u
source deployments-src/ci/utils
source /etc/profile.d/chruby.sh
chruby ruby

cp worker-state/*.json updated-worker-state/worker-state.json

echo "Updating WORKER..."
bosh -n create-env \
  --state updated-worker-state/worker-state.json \
  -v concourse_release_path="$( realpath $PWD/concourse/*.tgz )" \
  -v garden_runc_release_path="$( realpath $PWD/garden-runc-release/*.tgz )" \
  -v bosh_cpi_release_path="$( realpath $PWD/bosh-cpi-release/*.tgz )" \
  -v stemcell_path="$( realpath $PWD/stemcell/*.tgz )" \
  -l <( echo "${WORKER_SECRETS}" ) \
  $( echo ${OPTIONAL_FLAGS} ) \
  --vars-store="creds.yml" \
  deployments-src/concourse/workers/${ENVIRONMENT_NAME}/worker.yml

echo "Successfully updated worker!"
