#!/bin/bash

set -eu

# env
: ${GOOGLE_CREDENTIALS:?}
: ${JUMPBOX_SECRETS:?}
: ${JUMPBOX_PUBLIC_KEY:?}
: ${TRUSTED_CIDRS:?}

source deployments-src/ci/utils

remove_terraform_prefix terraform/metadata jumpbox_ > metadata

cp jumpbox-state/*.json updated-jumpbox-state
echo "Updating jumpbox..."
bosh2 -n create-env \
  --state updated-jumpbox-state/jumpbox-state.json \
  -o jumpbox-deployment-src/gcp/cpi.yml \
  -o deployments-src/jumpbox/iptables-ops.yml \
  -o deployments-src/jumpbox/custom-type-ops.yml \
  -l metadata \
  -l <( echo "${JUMPBOX_SECRETS}" ) \
  -l <( echo "${JUMPBOX_PUBLIC_KEY}" ) \
  -v "gcp_credentials_json='${GOOGLE_CREDENTIALS}'" \
  -v "trusted_cidrs='${TRUSTED_CIDRS}'" \
  -v "machine_type='${MACHINE_TYPE}'" \
  jumpbox-deployment-src/jumpbox.yml

echo "Successfully updated jumpbox!"
