#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${GOOGLE_CREDENTIALS_JSON:?}
: ${NATBOX_SECRETS:?}

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
nat_state_dir="$( cd "${workspace_dir}/natbox-state" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_dir="$( cd "${workspace_dir}/updated-natbox-state" && pwd )"

cp ${nat_state_dir}/*.json "${output_dir}"

pushd "${workspace_dir}" > /dev/null
  echo "Updating NAT..."
  ${bosh_cli} -n create-env \
    --state "${output_dir}/natbox-state.json" \
    -l "${terraform_config}/metadata" \
    -l <( echo "${NATBOX_SECRETS}" ) \
    -v "gcp_credentials_json='${GOOGLE_CREDENTIALS_JSON}'" \
    ${deployments_dir}/natbox/natbox.yml
popd > /dev/null

echo "Successflly updated nat!"
