#!/usr/bin/env bash

set -eu

: ${DEPLOYMENT_NAME:?}
: ${DEPLOYMENT_CONFIG_PATH:?}
: ${CONCOURSE_SECRETS:?}
: ${BOSH_ENVIRONMENT:?}
: ${BOSH_CLIENT:?}
: ${BOSH_CLIENT_SECRET:?}
: ${BOSH_CA_CERT:?}
: ${JUMPBOX_HOST:?}
: ${JUMPBOX_SSH_USER:?}
: ${JUMPBOX_SSH_KEY:?}
: ${CONCOURSE_EXTERNAL_URL:?}
: ${CONCOURSE_BASIC_AUTH_USERNAME:?}
: ${CONCOURSE_BASIC_AUTH_PASSWORD:?}
: ${CONCOURSE_GITHUB_CLIENT_ID:?}
: ${CONCOURSE_GITHUB_CLIENT_SECRET:?}
: ${CONCOURSE_TEAMS:?}

source deployments-src/ci/utils

terraform_metadata="$( realpath terraform/metadata )"
stemcell_version="$( cat stemcell/version )"
concourse_version="$( cat concourse/version )"
garden_version="$( cat garden-runc-release/version )"

setup_ssh_tunnel "$JUMPBOX_SSH_KEY" "$JUMPBOX_SSH_USER@$JUMPBOX_HOST"

set +e

echo "Uploading Concourse release..."
bosh -n --tty upload-release concourse/*.tgz

echo "Uploading Garden release..."
bosh -n --tty upload-release garden-runc-release/*.tgz

echo "Uploading Windows Tools release..."
bosh -n --tty upload-release windows-tools/*.tgz

echo "Uploading Windows Utilities release..."
( cd windows-utilities ; bosh -n --tty upload-release )

echo "Uploading stemcell..."
bosh -n --tty upload-stemcell stemcell/*.tgz

echo "Uploading Windows stemcell..."
bosh -n --tty upload-stemcell windows-stemcell/*.tgz

set -e

create_worker_ops_file() {
  local concourse_teams=${1?'Concourse teams is required.'}

  touch worker-ops.yml

  for ((i = 0 ; i < $(echo "$concourse_teams" | jq -r length) ; i++ )); do
    team="$(echo "$concourse_teams" | jq -r ".[$i]")"

    # if there is 'vm_type' create worker for team
    if [[ -n "$(echo "$team" | jq -r .vm_type)" ]]; then
      team_name="$(echo "$team" | jq -r .name)"
      bosh int \
        -l <( echo "$team" | jq '. + {"team": .name}' ) \
        deployments-src/concourse/worker-ops.yml >> worker-ops.yml
    fi

    # if 'worker_public_key' add to 'tsa.team_authorized_keys'
    if [[ -n "$(echo "$team" | jq -r .worker_public_key)" ]]; then
      bosh int \
        -l <( echo "$team" | jq '. + {"team": .name}' ) \
        deployments-src/concourse/team-authorized-public-key-ops.yml >> worker-ops.yml
    fi
  done

  realpath worker-ops.yml
}

echo "Building Concourse Workers manifest..."
worker_ops_path="$( create_worker_ops_file "$CONCOURSE_TEAMS" )"

pushd deployments-src > /dev/null
  echo "Deploying Concourse..."
  bosh -n --tty deploy \
    -l <(echo "${CONCOURSE_SECRETS}") \
    -v concourse_external_url=${CONCOURSE_EXTERNAL_URL} \
    -v concourse_basic_auth_username=${CONCOURSE_BASIC_AUTH_USERNAME} \
    -v concourse_basic_auth_password=${CONCOURSE_BASIC_AUTH_PASSWORD} \
    -v concourse_github_client_id=${CONCOURSE_GITHUB_CLIENT_ID} \
    -v concourse_github_client_secret=${CONCOURSE_GITHUB_CLIENT_SECRET} \
    -v stemcell_version="'${stemcell_version}'" \
    -v concourse_version="'${concourse_version}'" \
    -v garden_version="'${garden_version}'" \
    -d "${DEPLOYMENT_NAME}" \
    -o "$worker_ops_path" \
    --vars-store="you-really-need-this-flag-but-not-this-file.yml" \
    "${DEPLOYMENT_CONFIG_PATH}"
  echo "Successfully deployed Concourse!"
popd > /dev/null
