#!/bin/bash

set -eu

# env
: ${GOOGLE_CREDENTIALS:?}
: ${JUMPBOX_SECRETS:?}
: ${JUMPBOX_PUBLIC_KEY:?}
: ${TRUSTED_CIDRS:?}

source deployments-src/ci/utils

tmp_dir="$( mktemp -d /tmp/deploy-jumpbox-XXXXXXXX)"
trap "{ cleanup_tmp_dir $tmp_dir; }" EXIT

cp jumpbox-state/*.json updated-jumpbox-state

# remove `jumpbox_` prefix from keys to conform to jumpbox-deployment templates
terraform_metadata="${tmp_dir}/terraform_metadata"
jq 'with_entries(.key |= sub("^jumpbox_"; ""))' terraform/metadata > "${terraform_metadata}"

pushd "${workspace_dir}" > /dev/null
  echo "Updating jumpbox..."
  ${bosh_cli} -n create-env \
    --state updated-jumpbox-state/jumpbox-state.json \
    -o jumpbox-deployment-src/gcp/cpi.yml \
    -o deployments-src/jumpbox/iptables-opts.yml \
    -o deployments-src/jumpbox/custom-type-opts.yml \
    -l "${terraform_metadata}" \
    -l <( echo "${JUMPBOX_SECRETS}" ) \
    -l <( echo "${JUMPBOX_PUBLIC_KEY}" ) \
    -v "gcp_credentials_json='${GOOGLE_CREDENTIALS}'" \
    -v "trusted_cidrs='${TRUSTED_CIDRS}'" \
    -v "machine_type='${MACHINE_TYPE}'" \
    jumpbox-deployment-src/jumpbox.yml
popd > /dev/null

echo "Successfully updated jumpbox!"
