#!/usr/bin/env bash

set -eu

: ${BOSH_CLIENT:?}
: ${BOSH_CLIENT_SECRET:?}
: ${BOSH_CA_CERT:?}
: ${JUMPBOX_SSH_USER:?}
: ${JUMPBOX_SSH_KEY:?}
: ${VPN_SECRETS:?}

source deployments-src/ci/utils

terraform_metadata="$( realpath terraform/metadata )"
stemcell_version="$( cat stemcell/version )"

export BOSH_ENVIRONMENT="$( jq -r -e .director_internal_ip $terraform_metadata )"

setup_ssh_tunnel \
  "$JUMPBOX_SSH_KEY" \
  "$JUMPBOX_SSH_USER@$( jq -r -e .jumpbox_external_ip $terraform_metadata )"

echo "Uploading OpenVPN release..."
bosh2 -n --tty upload-release openvpn-release/release.tgz

echo "Uploading Networking release..."
bosh2 -n --tty upload-release networking-release/release.tgz

echo "Uploading SSOCA release..."
( cd ssoca; bosh2 -n --tty upload-release )

echo "Uploading stemcell..."
bosh2 -n --tty upload-stemcell stemcell/stemcell.tgz

pushd deployments-src > /dev/null
  echo "Deploying OpenVPN Server..."
  bosh2 -n --tty deploy -d openvpn \
    -l <(echo "${VPN_SECRETS}") \
    -v stemcell_version="$stemcell_version" \
    -l "$terraform_metadata" \
    --vars-store="you-really-need-this-flag-but-not-this-file.yml" \
    vpn/manifest.yml
  echo "Successfully deployed OpenVPN Server!"
popd > /dev/null
