#!/usr/bin/env bash

set -eu

: ${DEPLOYMENT_NAME:?}
: ${DEPLOYMENT_CONFIG_PATH:?}
: ${CONCOURSE_SECRETS:?}
: ${BOSH_CLIENT:?}
: ${BOSH_CLIENT_SECRET:?}
: ${BOSH_CA_CERT:?}
: ${JUMPBOX_SSH_USER:=vcap}
: ${JUMPBOX_SSH_KEY:?}
: ${CONCOURSE_EXTERNAL_URL:?}
: ${CONCOURSE_BASIC_AUTH_USERNAME:?}
: ${CONCOURSE_BASIC_AUTH_PASSWORD:?}
: ${CONCOURSE_TEAMS:?}

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
release_dir="$( cd "${workspace_dir}/concourse-and-garden" && pwd )"
stemcell_dir="$( cd "${workspace_dir}/stemcell" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

tmp_dir="$( mktemp -d /tmp/deploy-concourse-XXXXXXXX)"
cleanup_tmp_dir() {
  rm -rf "${tmp_dir}" || true
}
trap "{ cleanup_tmp_dir; }" EXIT # will be overridden by future trap calls

ssh_key_path="${tmp_dir}/id_rsa.pem"
echo "${JUMPBOX_SSH_KEY}" > "${ssh_key_path}"
chmod 400 "${ssh_key_path}"

terraform_metadata="${terraform_config}/metadata"
jumpbox_external_ip=$( jq -r -e .jumpbox_external_ip ${terraform_metadata} )
director_internal_ip=$( jq -r -e .director_internal_ip ${terraform_metadata} )

jumpbox_address="${JUMPBOX_SSH_USER}@${jumpbox_external_ip}"
ssh_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${ssh_key_path}"
ssh ${ssh_args} -M -S "${tmp_dir}/tunnel-socket" -fnNT -L 25555:${director_internal_ip}:25555 "${jumpbox_address}"
cleanup_ssh_tunnel() {
  ssh ${ssh_args} -S "${tmp_dir}/tunnel-socket" -O exit "${jumpbox_address}"
}
trap "{ cleanup_ssh_tunnel; cleanup_tmp_dir; }" EXIT

export BOSH_ENVIRONMENT="127.0.0.1"

echo "Restarting TSA"
${bosh_cli} -n --tty restart \
  -d "${DEPLOYMENT_NAME}" concourse_cpi
