#!/usr/bin/env bash

set -eu

pushd deployments-src/concourse/teams/core
  wget -O ./fly "${CONCOURSE_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"
  chmod +x ./fly

  yes | ./fly -t concourse login \
    -c "${CONCOURSE_EXTERNAL_URL}" \
    -u "${CONCOURSE_BASIC_AUTH_USERNAME}" \
    -p "${CONCOURSE_BASIC_AUTH_PASSWORD}"


  ./fly -t concourse set-team  --non-interactive -n bosh-io -c bosh-io.yml
  ./fly -t concourse set-team  --non-interactive -n bosh-packages -c bosh-packages.yml
  ./fly -t concourse set-team  --non-interactive -n dev -c dev.yml
  ./fly -t concourse set-team  --non-interactive -n main -c main.yml
  ./fly -t concourse set-team  --non-interactive -n pcf -c pcf.yml
  ./fly -t concourse set-team  --non-interactive -n bosh-director -c bosh-director.yml
popd

