#!/usr/bin/env bash

set -eu

source deployments-src/ci/utils
: ${CONCOURSE_EXTERNAL_URL:?}
: ${CONCOURSE_BASIC_AUTH_USERNAME:?}
: ${CONCOURSE_BASIC_AUTH_PASSWORD:?}
: ${CONCOURSE_TEAMS:-"[]"}
: ${CONCOURSE_GITHUB_CLIENT_ID:?}
: ${CONCOURSE_GITHUB_CLIENT_SECRET:?}

wget -O ./fly "${CONCOURSE_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"
chmod +x ./fly

yes | ./fly -t concourse login \
  -c "${CONCOURSE_EXTERNAL_URL}" \
  -u "${CONCOURSE_BASIC_AUTH_USERNAME}" \
  -p "${CONCOURSE_BASIC_AUTH_PASSWORD}"

iterate_teams "$CONCOURSE_TEAMS" \
  set_team concourse "${CONCOURSE_GITHUB_CLIENT_ID}" "${CONCOURSE_GITHUB_CLIENT_SECRET}"
