#!/usr/bin/env bash

set -eu

: ${CONCOURSE_EXTERNAL_URL:?}
: ${CONCOURSE_BASIC_AUTH_USERNAME:?}
: ${CONCOURSE_BASIC_AUTH_PASSWORD:?}
: ${CONCOURSE_TEAMS:?}
: ${CONCOURSE_GITHUB_CLIENT_ID:?}
: ${CONCOURSE_GITHUB_CLIENT_SECRET:?}

wget -O ./fly "${CONCOURSE_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"
chmod +x ./fly

yes | ./fly -t concourse login \
  -c "${CONCOURSE_EXTERNAL_URL}" \
  -u "${CONCOURSE_BASIC_AUTH_USERNAME}" \
  -p "${CONCOURSE_BASIC_AUTH_PASSWORD}"

if [[ -n "${CONCOURSE_TEAMS}" ]]; then
  for ((i = 0 ; i < $(echo "$CONCOURSE_TEAMS" | jq -r length) ; i++ )); do
    team="$(echo "$CONCOURSE_TEAMS" | jq -r ".[$i]")"

    yes | ./fly -t concourse set-team \
      --team-name="$( echo "$team" | jq -r .name )" \
      --github-auth-team="$( echo "$team" | jq -r .github_team )" \
      --github-auth-client-id="${CONCOURSE_GITHUB_CLIENT_ID}" \
      --github-auth-client-secret="${CONCOURSE_GITHUB_CLIENT_SECRET}"
  done
fi
