#!/bin/bash

set -eu

# env
: ${BOSH_CLIENT:?}
: ${BOSH_CLIENT_SECRET:?}
: ${BOSH_CA_CERT:?}
: ${JUMPBOX_SSH_USER:?}
: ${JUMPBOX_SSH_KEY:?}

source deployments-src/ci/utils

terraform_metadata="$( realpath terraform/metadata )"

export BOSH_ENVIRONMENT="$( jq -r -e .director_internal_ip $terraform_metadata )"

setup_ssh_tunnel \
  "$JUMPBOX_SSH_KEY" \
  "$JUMPBOX_SSH_USER@$( jq -r -e .jumpbox_external_ip $terraform_metadata )"

echo "Updating cloud config..."
bosh2 -n update-cloud-config \
  -l "${terraform_metadata}" \
  deployments_dir/bosh/cloud-config.yml

echo "Successfully updated cloud-config!"
