#!/bin/bash

set -eu -o pipefail

# env
: ${SLEEP_TIME:?}
: ${JUMPBOX_HOST:?}

echo "Your jumpbox address is '${JUMPBOX_HOST}'."
echo "We'll leave the SSH port open for $(( ${SLEEP_TIME} / 60 )) minutes."
echo "Hit cancel once to close the SSH port early"
echo "😴 ..."
sleep "${SLEEP_TIME}"
