#!/bin/bash

set -eu -o pipefail

# env
: ${SLEEP_TIME:?}

deployments_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# inputs
jumpbox_external_ip=$(jq -r -e .jumpbox_external_ip ${workspace_dir}/terraform/metadata)

echo "Your jumpbox address is '${jumpbox_external_ip}'."
echo "We'll leave the SSH port open for $(( ${SLEEP_TIME} / 60 )) minutes."
echo "Hit cancel once to close the SSH port early"
echo "😴 ..."
sleep "${SLEEP_TIME}"
