#!/usr/bin/env bash

set -eu

source $REPO_DIR/ci/utils
UPGRADER_CREATE_ENV_SECURE_NOTE=bosh-concourse-upgrader-create-env

load_create_env_var() {
  local path=${1?"path required: e.g. '/var'"}
  bosh2 int <( lpass show --note "$UPGRADER_CREATE_ENV_SECURE_NOTE" ) --path $path
}

: ${concourse_external_url=$( load_create_env_var /external_url )}
: ${concourse_teams=$( load_create_env_var /concourse_teams )}
: ${concourse_github_client_id=$( load_create_env_var /github_auth_client_id )}
: ${concourse_github_client_secret=$( load_create_env_var /github_auth_client_secret )}

bosh2 create-env ./upgrader.yml \
  -l <( lpass show --notes "$UPGRADER_CREATE_ENV_SECURE_NOTE" ) \
  --state ./upgrader-state.json

wget -O ./fly "${concourse_external_url}/api/v1/cli?arch=amd64&platform=darwin"
chmod +x ./fly

./fly -t upgrader login -c "${concourse_external_url}"

set_concourse_teams \
  upgrader \
  "$concourse_teams" \
  "${concourse_github_client_id}" \
  "${concourse_github_client_secret}"

echo '# Generated $( date )' >> ./upgrader-state.json

echo "Finished successfully"
echo "Remember to commit the statefile changes when deploy is finished!"

rm ./fly
