---
name: concourse-core

releases:
- name: concourse
  version: 3.4.1
- name: garden-runc
  version: 1.6.0
- name: ulimit
  version: latest
- name: windows-utilities
  version: latest
- name: slack-notification-resource
  version: 9
  url: http://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b

# github.com/greenhouse-org/concourse-windows-release
- name: concourse-windows-worker
  version: 3.4.0

stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell_version))
# Windows Stemcell for AWS: https://s3.amazonaws.com/bosh-windows-stemcells/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- alias: windows
  os: windows2012R2
  version: latest

update:
  canaries: 1
  max_in_flight: 8
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000
  serial: false

instance_groups:
- name: atc
  instances: 1
  vm_type: concourse_core
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: atc
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        bind_port: 80
        tls_bind_port: 443
        tls_cert: ((tls_cert))
        tls_key: ((tls_key))
        publicly_viewable: true
        postgresql_database: &atc_db ((database_name))
        github_auth:
          client_id: ((github_auth_client_id))
          client_secret: ((github_auth_client_secret))
          authorize: ((github_auth_authorize_organizations))
    - name: tsa
      release: concourse
      properties:
        authorized_keys: ((tsa_authorized_keys))
        host_key: ((tsa_host_key))
        host_public_key: ((tsa_host_public_key))
    - name: ulimit
      release: ulimit
      properties:
        nofile:
          soft: 32768
          hard: 32768

- name: database
  instances: 1
  vm_type: concourse_core_database
  stemcell: default
  azs: [us1]
  persistent_disk_pool: persistent
  networks:
    - name: concourse
  jobs:
    - name: postgresql
      release: concourse
      properties:
        listen_host: 127.0.0.1
        databases:
          - name: *atc_db
            role: ((database_role))
            password: ((database_password))

- name: worker
  instances: 4
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-default
      properties:
        additional_resource_types: &additional_resource_types
        - type: slack-notification
          image: /var/vcap/packages/slack-notification-resource
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
    - name: garden
      release: garden-runc
      properties: &garden
        garden:
          listen_network: tcp
          listen_address: 127.0.0.1:7777
          allow_host_access: true
          btrfs_store_size_mb: 1000000
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-default
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-btrfs
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-btrfs
      properties:
        additional_resource_types: &additional_resource_types
        - type: slack-notification
          image: /var/vcap/packages/slack-notification-resource
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - btrfs
    - name: garden
      release: garden-runc
      properties: &garden
        garden:
          listen_network: tcp
          listen_address: 127.0.0.1:7777
          allow_host_access: true
          btrfs_store_size_mb: 1000000
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-btrfs
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-brats
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-brats
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - worker-brats
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-brats
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-bosh-load-tests
  instances: 1
  vm_type: concourse_core_load_worker
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-bosh-load-tests
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-load-tests
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-bosh-load-tests
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-gonats
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-gonats
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - worker-gonats
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-gonats
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-1
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-1
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-1
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-1
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker_integration-2
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-2
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
          - bosh-integration
          - bosh-integration-2
          - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-2
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker_integration-3
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-3
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-3
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-3
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker_integration-4
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-4
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-4
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-4
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-5
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-5
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-5
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-5
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-6
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-6
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-6
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-6
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-7
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-7
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-7
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-7
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-8
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-8
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-8
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-8
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker_integration-9
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-9
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-9
        - fly-integration
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-9
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-dns-performance
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: groundcrew
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-dns-performance
      properties:
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
          - dns-performance
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties: {}
      provides:
        baggageclaim:
          as: baggageclaim-worker-dns-performance
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: windows_worker
  stemcell: windows
  vm_type: concourse_core_worker_8_16
  azs: [us1]
  networks:
  - name: concourse
  jobs:
  - name: concourse_windows
    release: concourse-windows-worker
  - name: set_password
    release: windows-utilities
    properties:
      set_password:
        username: "((windows_administrator_username))"
        password: "((windows_administrator_password))"
  instances: 1
  properties:
    concourse_windows:
      tsa_host: ((concourse_tsa_hostname))
      tsa_public_key: ((tsa_host_public_key))
      tsa_worker_private_key: ((tsa_worker_private_key))
