#!/bin/bash

if [[ $(lpass status -q; echo $?) != 0 ]]; then
  echo "Login with lpass first"
  exit 1
fi

fly -t upgrader sp \
  -p concourse-core \
  -c "$REPO_DIR/ci/pipeline-core.yml" \
  -l <(lpass show --note "bosh-concourse-deployments gcp bosh-core") \
  -l <(lpass show --note "bosh-concourse-deployments gcp bosh-core external workers")
