---
jobs:
  - name: prepare-concourse-env
    serial_groups: [deploy]
    plan:
      - aggregate:
        - get: deployments-src
        - get: jumpbox-deployment-src
        - get: bosh-cli
        - get: concourse-natbox-state
        - get: concourse-jumpbox-state
        - get: bosh-google-cpi-release
        - get: networking-release
        - get: stemcell
      - put: terraform
        params:
          env_name: bosh-cpi-concourse
          terraform_source: deployments-src/terraform/concourse
          vars:
            allow_mbus_access_to_natbox: 1
            allow_mbus_access_to_jumpbox: 1
      - aggregate:
        - task: update-natbox
          file: deployments-src/ci/tasks/deploy-natbox.yml
          input_mapping:
            natbox-state: concourse-natbox-state
          params:
            GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
          ensure:
            put: concourse-natbox-state
            params:
              file: updated-natbox-state/natbox-state.json
        - task: update-jumpbox
          file: deployments-src/ci/tasks/deploy-jumpbox.yml
          input_mapping:
            jumpbox-state: concourse-jumpbox-state
          params:
            TEAMS:              {{bosh_teams}}
            GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
            TRUSTED_CIDRS:      {{ssh_trusted_cidrs}}
            MACHINE_TYPE:       {{jumpbox_machine_type}}
          ensure:
            put: concourse-jumpbox-state
            params:
              file: updated-jumpbox-state/jumpbox-state.json
    ensure:
      put: terraform
      params:
        env_name: bosh-cpi-concourse
        terraform_source: deployments-src/terraform/concourse
        vars:
          allow_mbus_access_to_natbox: 0
          allow_mbus_access_to_jumpbox: 0

  - name: update-director
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: director-templates
          - get: bosh-cli
          - get: director-state
        - &open-ssh-to-jumpbox
          put: terraform
          params:
            env_name: bosh-cpi-concourse
            terraform_source: deployments-src/terraform/concourse
            vars:
              allow_ssh_access_to_jumpbox: 1
        - task: update-director
          file: deployments-src/ci/tasks/deploy-director.yml
          params:
            GOOGLE_CREDENTIALS:      {{gcp_credentials_json}}
            BOSH_DIRECTOR_SECRETS:   {{bosh_director_secrets}}
            BOSH_CLIENT:             {{bosh_client}}
            BOSH_CLIENT_SECRET:      {{bosh_client_secret}}
            BOSH_CA_CERT:            {{bosh_ca_cert}}
            BOSH_CA_KEY:             {{director_ca_key}}
            JUMPBOX_SSH_KEY:         {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:        {{jumpbox_ssh_user}}
            ADDITIONAL_OPS:          {{director_additional_ops_base64}}
            BOSH_TEAMS:              {{bosh_teams}}
          ensure:
            put: director-state
            params:
              file: updated-director-state/bosh-state.json
            ensure: &close-ssh-to-jumpbox
              put: terraform
              params:
                env_name: bosh-cpi-concourse
                terraform_source: deployments-src/terraform/concourse
                vars:
                  allow_ssh_access_to_jumpbox: 0

  - name: update-cloud-config
    serial_groups: [deploy]
    plan:
      - do:
        - aggregate:
          - get: deployments-src
          - get: bosh-cli
        - *open-ssh-to-jumpbox
        - &wait-for-ssh
          task: wait-for-ssh
          file: deployments-src/ci/tasks/wait-ssh.yml
          params:
            JUMPBOX_HOST: {{jumpbox_host}}
        - task: update-cloud-config
          file: deployments-src/ci/tasks/update-cloud-config.yml
          params:
            BOSH_CLIENT:           {{bosh_client}}
            BOSH_CLIENT_SECRET:    {{bosh_client_secret}}
            BOSH_CA_CERT:          {{bosh_ca_cert}}
            JUMPBOX_SSH_KEY:       {{jumpbox_ssh_key}}
            JUMPBOX_SSH_USER:      {{jumpbox_ssh_user}}
          ensure: *close-ssh-to-jumpbox

  - name: update-vpn-server
    serial_groups: [deploy]
    plan:
      - aggregate:
        - get: deployments-src
        - get: stemcell
        - get: bosh-cli
        - get: networking-release
        - get: openvpn-release
        - get: ssoca
      - *open-ssh-to-jumpbox
      - *wait-for-ssh
      - task: deploy-vpn-server
        file: deployments-src/ci/tasks/deploy-vpn-server.yml
        params:
          BOSH_CLIENT:        {{bosh_client}}
          BOSH_CLIENT_SECRET: {{bosh_client_secret}}
          BOSH_CA_CERT:       {{bosh_ca_cert}}
          JUMPBOX_SSH_KEY:    {{jumpbox_ssh_key}}
          JUMPBOX_SSH_USER:   {{jumpbox_ssh_user}}
          VPN_SECRETS:        {{cpi_vpn_secrets}}
    ensure: *close-ssh-to-jumpbox

  - name: open-ssh-for-30m
    serial_groups: [deploy]
    plan:
      - get: deployments-src
      - *open-ssh-to-jumpbox
      - task: wait-for-ssh
        file: deployments-src/ci/tasks/wait-for-ssh.yml
        params:
          JUMPBOX_HOST: {{jumpbox_host}}
    ensure: *close-ssh-to-jumpbox

  - name: re-terraform
    serial_groups: [deploy, deploy-asia]
    plan:
      - aggregate:
        - get: every-2-hours
          trigger: true
        - get: deployments-src
      - task: delete-firewall-rules
        file: deployments-src/ci/tasks/delete-firewall-rules.yml
        params:
          GOOGLE_PROJECT_ID: {{project_id}}
          GOOGLE_CREDENTIALS: {{gcp_credentials_json}}
    ensure:
      do:
      - *close-ssh-to-jumpbox

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
      branch: master
  - name: director-templates
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: master
  - name: jumpbox-deployment-src
    type: git
    source:
      uri: https://github.com/cppforlife/jumpbox-deployment.git
      branch: master
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        project_id: {{project_id}}
        gcp_credentials_json: {{gcp_credentials_json}}
        ssh_trusted_cidrs: {{ssh_trusted_cidrs}}
        create_env_trusted_cidrs: {{create_env_trusted_cidrs}}
        bosh_cpi_web_trusted_cidrs: {{bosh_cpi_web_trusted_cidrs}}
        bosh_core_web_trusted_cidrs: {{bosh_core_web_trusted_cidrs}}
  - name: concourse-natbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: concourse/natbox-state.json
  - name: concourse-jumpbox-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: concourse/jumpbox-state.json
  - name: director-state
    type: gcs-resource
    source:
      bucket: {{deployments_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: director/bosh-state.json
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
  - name: bosh-google-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release
  - name: networking-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/networking-release
  - name: openvpn-release
    type: bosh-io-release
    source:
      repository: dpb587/openvpn-bosh-release
  - name: ssoca
    type: git
    source:
      uri: https://github.com/dpb587/ssoca-bosh-release.git
      branch: master
  - name: every-2-hours
    type: time
    source:
      interval: 2h
