---
jobs:
- name: renew-lease-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
      - get: every-day
        trigger: true
    - task: extend-lease
      file: deployments-src/ci/tasks/extend-lease-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: ((nimbus-user))
        NIMBUS_LOCATION: ((nimbus-location))

- name: create-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
    - task: testbed-cleanup
      file: deployments-src/ci/tasks/cleanup-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: ((nimbus-user)) # TODO change to service account
        NIMBUS_LOCATION: ((nimbus-location))
    - task: testbed-deploy
      file: deployments-src/ci/tasks/deploy-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: ((nimbus-user)) # TODO change to service account
        NIMBUS_LOCATION: ((nimbus-location))
    - put: vsphere-v7.0-worker-state-1
      params:
        file: worker-state/clean-env
    - put: testbed-info
      params:
        file: nimbus-testbed-info/testbedInfo.json
    - task: create-nimbus-vcenter-vars
      file: deployments-src/ci/tasks/create-nimbus-vcenter-vars.yml
      params:
        VCENTER_PASSWORD: ((vcenter-password))
    - put: nimbus-vcenter-vars
      params:
        file: nimbus-vcenter-vars/nimbus-vcenter-vars.yml

- name: update-vsphere-v7.0-worker
  serial: true
  plan:
    - do:
      - in_parallel:
        - get: concourse
        - get: deployments-src
        - get: bosh-cli
        - get: testbed-info
          trigger: true
        - get: vsphere-v7.0-worker-state-1
        - get: bosh-cpi-release
          resource: bosh-vsphere-cpi-release
        - get: stemcell
          resource: vsphere-xenial-stemcell
      - in_parallel:
        - task: update-vsphere-v7.0-worker-1
          file: deployments-src/ci/tasks/deploy-worker.yml
          input_mapping:
            worker-state: vsphere-v7.0-worker-state-1
          params:
            WORKER_SECRETS: ((vsphere-v70-worker-secrets-1))
            ENVIRONMENT_NAME: nimbus
          ensure:
            put: vsphere-v7.0-worker-state-1
            params:
              file: updated-worker-state/worker-state.json

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/frodenas/gcs-resource

resources:
- name: every-day
  type: time
  source:
    interval: 24h
- name: deployments-src
  type: git
  source:
    uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
    branch: master
- name: testbed-info
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: nimbus/testbed-info.json
- name: nimbus-vcenter-vars
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: nimbus-vcenter-vars.yml

- name: vsphere-v7.0-worker-state-1
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: worker/vsphere-v7.0-worker-state-1.json
- name: bosh-cli
  type: s3
  source:
    bucket: bosh-cli-artifacts
    regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
- name: vsphere-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent
- name: concourse
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release
- name: bosh-vsphere-cpi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-vsphere-cpi-release
