#!/usr/bin/env bash

set_concourse_teams() {
  local concourse_target=${1?'Concourse target is required.'}
  local concourse_teams=${2?'Concourse teams are required.'}
  local concourse_github_client_id=${3?'Concourse GitHub Client ID is required.'}
  local concourse_github_client_secret=${4?'Concourse GitHub Client Secret is required.'}

  for ((i = 0 ; i < $(echo "$concourse_teams" | jq -r length) ; i++ )); do
    team="$(echo "$concourse_teams" | jq -r ".[$i]")"

    yes | ./fly -t $concourse_target set-team \
      --team-name="$( echo "$team" | jq -r .name )" \
      --github-auth-team="$( echo "$team" | jq -r .github_team )" \
      --github-auth-client-id="${concourse_github_client_id}" \
      --github-auth-client-secret="${concourse_github_client_secret}"
  done
}
